Fix #20 : Added "unreachable" ErrorType and regex.
point-source/dart_ping pull request #43
Opened 2023-02-01 14:30 UTC by ckerens

2023-02-02 23:03 UTC, point-source requested changes
Please update the readme. Particularly the parser override section, if possible.

2023-02-02 23:03 UTC, point-source commented on dart_ping/lib/src/models/ping_parser.dart
> +          if (data.contains(unreachableStr)) {
These if statement should probably become if/else unless we can guarantee that the presence of one truthy contains() negates the others. Reason being that we don't want one line of ping output to result in two separate PingData events.

2023-02-06 21:12 UTC, ckerens commented
I can take care of this sometime in the next few days.  Currently deep in another project, but I agree on the requested changes.

2026-06-22 21:00 UTC, point-source commented
closing as the refactor for v10 has resolved this implicitly

2026-06-22 21:00 UTC, closed without merging